<img src="../../images/scipylogo.png" align="center" width="90%">

# Welcome to the Xarray SciPy 2022 Tutorial! 

**Xarray**: *Friendly, Interactive, and Scalable Scientific Data Analysis*

Learning goals:
- understand the Xarray data model
- effectively use Xarray’s multidimensional labeled indexing
- utilize Xarray’s powerful built-in computational methods
- learn about the ecosystem of software extending Xarray

This *4-hour* workshop will explore content from https://tutorial.xarray.dev, which contains a comprehensive collection of hands-on tutorial Jupyter Notebooks. We won't cover it all today, but instead will review a curated set of examples that will prepare you for increasingly complex real-world data analysis tasks!


## Schedule 
*Times in Central Daylight (Austin, TX)

| Topic | Time | Notebook Links | 
| :- | - | - | 
| Introduction | 1:30 (20 min) | [getting started](../../overview/get-started.md) | 
| Data Structures | 1:50 (30 min) | [datastructures](../../fundamentals/01_datastructures.ipynb) <br> [input/output](../../fundamentals/01.1_io.ipynb) | 
| *Break*  
| Labeled Data | 2:30 (20 min) | [working_with_labeled_data](../../fundamentals/02.1_working_with_labeled_data.ipynb) | 
| Visualizations | 2:50 (30 min) | [basic_plotting](../../fundamentals/04.1_basic_plotting.ipynb) <br> [facet plots](../../fundamentals/04.2_faceting.ipynb) | 
| *Break*  | 
| Computation | 3:30 (50 min) | [computation with xarray](../../fundamentals/03.1_computation_with_xarray.ipynb) <br> [aligning data objects](../../fundamentals/02.3_aligning_data_objects.ipynb) <br> [groupby with xarray](../../fundamentals/03.2_groupby_with_xarray.ipynb) |  
| *Break*  | 
| Xarray ecosystem | 4:30 (30 min) | [xarray ecosystem](../../intermediate/xarray_ecosystem.ipynb) | 
| Scaling Xarray | 5:00 (20 min) |  | 
| | **End 5:30** | |

**Thanks for attending!**

Please continue to explore the subfolders in the JupyterLab File Browser for additional tutorial notebooks to run, or read the rendered notebooks at https://tutorial.xarray.dev

In [1]:
import xarray as xr


In [2]:
dir(xr.DataArray)

['T',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__dask_graph__',
 '__dask_keys__',
 '__dask_layers__',
 '__dask_optimize__',
 '__dask_postcompute__',
 '__dask_postpersist__',
 '__dask_scheduler__',
 '__dask_tokenize__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__

In [25]:
help(xr.DataArray.rename)

Help on function rename in module xarray.core.dataarray:

rename(self, new_name_or_name_dict: 'Hashable | Mapping[Any, Hashable]' = None, **names: 'Hashable') -> 'DataArray'
    Returns a new DataArray with renamed coordinates or a new name.
    
    Parameters
    ----------
    new_name_or_name_dict : str or dict-like, optional
        If the argument is dict-like, it used as a mapping from old
        names to new names for coordinates. Otherwise, use the argument
        as the new name for this array.
    **names : hashable, optional
        The keyword arguments form of a mapping from old names to
        new names for coordinates.
        One of new_name_or_name_dict or names must be provided.
    
    Returns
    -------
    renamed : DataArray
        Renamed array or array with renamed coordinates.
    
    See Also
    --------
    Dataset.rename
    DataArray.swap_dims



In [26]:
help(xr.DataArray.swap_dims)

Help on function swap_dims in module xarray.core.dataarray:

swap_dims(self, dims_dict: 'Mapping[Any, Hashable]' = None, **dims_kwargs) -> 'DataArray'
    Returns a new DataArray with swapped dimensions.
    
    Parameters
    ----------
    dims_dict : dict-like
        Dictionary whose keys are current dimension names and whose values
        are new names.
    **dims_kwargs : {existing_dim: new_dim, ...}, optional
        The keyword arguments form of ``dims_dict``.
        One of dims_dict or dims_kwargs must be provided.
    
    Returns
    -------
    swapped : DataArray
        DataArray with swapped dimensions.
    
    Examples
    --------
    >>> arr = xr.DataArray(
    ...     data=[0, 1],
    ...     dims="x",
    ...     coords={"x": ["a", "b"], "y": ("x", [0, 1])},
    ... )
    >>> arr
    <xarray.DataArray (x: 2)>
    array([0, 1])
    Coordinates:
      * x        (x) <U1 'a' 'b'
        y        (x) int64 0 1
    
    >>> arr.swap_dims({"x": "y"})
    <xarray.DataA

In [9]:
help(xr.DataArray.prod)

Help on function prod in module xarray.core.common:

prod(self, dim=None, axis=None, skipna=None, **kwargs)
    Reduce this DataArray's data by applying `prod` along some dimension(s).
    
    Parameters
    ----------
    dim : str or sequence of str, optional
        Dimension(s) over which to apply `prod`.
    axis : int or sequence of int, optional
        Axis(es) over which to apply `prod`. Only one of the 'dim'
        and 'axis' arguments can be supplied. If neither are supplied, then
        `prod` is calculated over axes.
    skipna : bool, optional
        If True, skip missing values (as marked by NaN). By default, only
        skips missing values for float dtypes; other dtypes either do not
        have a sentinel missing value (int) or skipna=True has not been
        implemented (object, datetime64 or timedelta64).
    min_count : int, default: None
        The required number of valid values to perform the operation. If
        fewer than min_count non-NA values are p

In [4]:
xr.DataArray.outer

AttributeError: type object 'DataArray' has no attribute 'outer'

In [10]:
import numpy as np

In [14]:
np.arange(20).reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
a = xr.DataArray(
    data=np.arange(20).reshape((4, 5)),
    coords={"x": [1,2,3,4], "y": [4,5,6,7,8]}
)
a

<xarray.DataArray (x: 4, y: 5)>
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])
Coordinates:
  * x        (x) int64 1 2 3 4
  * y        (y) int64 4 5 6 7 8

In [17]:
b = xr.DataArray(
    data=np.arange(20).reshape((4, 5)),
    coords={"p": [1,2,3,4], "q": [4,5,6,7,8]}
)
b

<xarray.DataArray (p: 4, q: 5)>
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])
Coordinates:
  * p        (p) int64 1 2 3 4
  * q        (q) int64 4 5 6 7 8

In [18]:
a * b

<xarray.DataArray (x: 4, y: 5, p: 4, q: 5)>
array([[[[  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0]],

        [[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[  0,   2,   4,   6,   8],
         [ 10,  12,  14,  16,  18],
         [ 20,  22,  24,  26,  28],
         [ 30,  32,  34,  36,  38]],

        [[  0,   3,   6,   9,  12],
         [ 15,  18,  21,  24,  27],
         [ 30,  33,  36,  39,  42],
         [ 45,  48,  51,  54,  57]],

...

        [[  0,  16,  32,  48,  64],
         [ 80,  96, 112, 128, 144],
         [160, 176, 192, 208, 224],
         [240, 256, 272, 288, 304]],

        [[  0,  17,  34,  51,  68],
         [ 85, 102, 119, 136, 153],
         [170, 187, 204, 221, 238],
         [255, 272, 289, 306, 323]],

        [[  0,  18,  36,  54,  72],
         [ 90, 108, 126, 144, 162],
         [180, 198, 216, 234, 252],
         [270, 288, 306, 324, 342]],

        [[  0,  19,  38,  57,  76],
         [ 95, 114, 133, 152, 171],
         [190, 209, 228, 247, 266],
         [285, 304, 323, 342, 361]]]])
Coordinates:
  * x        (x) int64 1 2 3 4
  * y        (y) int64 4 5 6 7 8
  * p        (p) int64 1 2 3 4
  * q        (q) int64 4 5 6 7 8

In [19]:
a@b

<xarray.DataArray (x: 4, y: 5, p: 4, q: 5)>
array([[[[  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0]],

        [[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[  0,   2,   4,   6,   8],
         [ 10,  12,  14,  16,  18],
         [ 20,  22,  24,  26,  28],
         [ 30,  32,  34,  36,  38]],

        [[  0,   3,   6,   9,  12],
         [ 15,  18,  21,  24,  27],
         [ 30,  33,  36,  39,  42],
         [ 45,  48,  51,  54,  57]],

...

        [[  0,  16,  32,  48,  64],
         [ 80,  96, 112, 128, 144],
         [160, 176, 192, 208, 224],
         [240, 256, 272, 288, 304]],

        [[  0,  17,  34,  51,  68],
         [ 85, 102, 119, 136, 153],
         [170, 187, 204, 221, 238],
         [255, 272, 289, 306, 323]],

        [[  0,  18,  36,  54,  72],
         [ 90, 108, 126, 144, 162],
         [180, 198, 216, 234, 252],
         [270, 288, 306, 324, 342]],

        [[  0,  19,  38,  57,  76],
         [ 95, 114, 133, 152, 171],
         [190, 209, 228, 247, 266],
         [285, 304, 323, 342, 361]]]])
Coordinates:
  * x        (x) int64 1 2 3 4
  * y        (y) int64 4 5 6 7 8
  * p        (p) int64 1 2 3 4
  * q        (q) int64 4 5 6 7 8

In [20]:
a @ b == a * b

<xarray.DataArray (x: 4, y: 5, p: 4, q: 5)>
array([[[[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

...

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]]])
Coordinates:
  * x        (x) int64 1 2 3 4
  * y        (y) int64 4 5 6 7 8
  * p        (p) int64 1 2 3 4
  * q        (q) int64 4 5 6 7 8

In [21]:
a * b

<xarray.DataArray (x: 4, y: 5, p: 4, q: 5)>
array([[[[  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0]],

        [[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[  0,   2,   4,   6,   8],
         [ 10,  12,  14,  16,  18],
         [ 20,  22,  24,  26,  28],
         [ 30,  32,  34,  36,  38]],

        [[  0,   3,   6,   9,  12],
         [ 15,  18,  21,  24,  27],
         [ 30,  33,  36,  39,  42],
         [ 45,  48,  51,  54,  57]],

...

        [[  0,  16,  32,  48,  64],
         [ 80,  96, 112, 128, 144],
         [160, 176, 192, 208, 224],
         [240, 256, 272, 288, 304]],

        [[  0,  17,  34,  51,  68],
         [ 85, 102, 119, 136, 153],
         [170, 187, 204, 221, 238],
         [255, 272, 289, 306, 323]],

        [[  0,  18,  36,  54,  72],
         [ 90, 108, 126, 144, 162],
         [180, 198, 216, 234, 252],
         [270, 288, 306, 324, 342]],

        [[  0,  19,  38,  57,  76],
         [ 95, 114, 133, 152, 171],
         [190, 209, 228, 247, 266],
         [285, 304, 323, 342, 361]]]])
Coordinates:
  * x        (x) int64 1 2 3 4
  * y        (y) int64 4 5 6 7 8
  * p        (p) int64 1 2 3 4
  * q        (q) int64 4 5 6 7 8

In [24]:
(a * b) @ b

<xarray.DataArray (x: 4, y: 5)>
array([[    0,  2470,  4940,  7410,  9880],
       [12350, 14820, 17290, 19760, 22230],
       [24700, 27170, 29640, 32110, 34580],
       [37050, 39520, 41990, 44460, 46930]])
Coordinates:
  * x        (x) int64 1 2 3 4
  * y        (y) int64 4 5 6 7 8